//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//
import ObjectMapper

class Events: PaginationResponse {
    typealias Element = Event

    var hasNext: Bool = false

     var offset: Int = 0

     var limit: Int = 0

    var items: Array<Event> = []
    required convenience init?(map: Map) {
        self.init()
    }
}


extension Events: Mappable {

    func mapping(map: Map) {
        hasNext <- map["hasNext"]
        offset <- (map["offset"], IntStringTransform())
        limit <- (map["limit"], IntStringTransform())
        items <- (map["items"], ListTransform<Event>())
    }
}
